// You are given 2 inputs, instructions array and treasure_rooms array.
// Task is to find special rooms. Special room is a room which satisfies 2 conditions
// 1. It should have atleast 2 incoming edges, meaning atleast 2 rooms should have a connection to this room
// 2. Room should have a connection to a treasure room(list is given in treasure_rooms array).
 
// example:
// input:
// instructions = [
//     ['tulip', 'lily'],
//     ['lily', 'hibiscus']
//     ['rose', 'lily']
//     ['hibiscus', 'rose']
//     ['lotus', 'lily']
//     ['Jasmine', 'lotus']
//     ['Marigold', 'lotus']
// ]

// treasure_rooms = ['lily', 'hibiscus', 'tulip']
 
// Consider flower names to be rooms. Instructions ['tulip', 'lily'] means there is a edge from tulip to lily.
// Constraints: 
// - There will be only one outgoing connection from any room
// - There can be any number of incoming edges.
 

// Output: ['lily', 'lotus']


// Code Generated by Sidekick is for learning and experimentation purposes only.
function flower(instructions, treasure_rooms) {
    // Count how many times each room is a destination (incoming)
    const incoming = {};
    // Remember where each room points to (outgoing)
    const outgoing = {};

    for (const [from, to] of instructions) {
        outgoing[from] = to;
        // Count incoming edges for 'to'
        if (incoming[to] === undefined) incoming[to] = 0;
        incoming[to]++;
        // Make sure every room is in incoming, even if zero
        if (incoming[from] === undefined) incoming[from] = 0;
    }

    // Now, find rooms with at least 2 incoming edges
    const specialRooms = [];
    for (const room in incoming) {
        // Check: 2 or more incoming, and outgoing leads to a treasure room
        if (
            incoming[room] >= 2 &&
            outgoing[room] &&
            treasure_rooms.includes(outgoing[room])
        ) {
            specialRooms.push(room);
        }
    }

    return specialRooms;
}


// Code Generated by Sidekick is for learning and experimentation purposes only.
const instructions = [
    ['tulip', 'lily'],
    ['lily', 'hibiscus'],
    ['rose', 'lily'],
    ['hibiscus', 'rose'],
    ['lotus', 'lily'],
    ['Jasmine', 'lotus'],
    ['Marigold', 'lotus']
];
const treasure_rooms = ['lily', 'hibiscus', 'tulip'];
console.log(flower(instructions, treasure_rooms)); // ['lily', 'lotus']
